import QtQuick

/* 
  GENERATED BY WALLUST
  This file is a data container. Theme.qml watches this file
  and reloads whenever Wallust overwrites it.
*/

QtObject {
    readonly property color background: "#1C0000"
    readonly property color foreground: "#F4DADA"
    readonly property color cursor: "#D67373"

    readonly property color color0: "#1C0000"
    readonly property color color1: "#910000"
    readonly property color color2: "#B80C0C"
    readonly property color color3: "#C83333"
    readonly property color color4: "#D65151"
    readonly property color color5: "#E46F6F"
    readonly property color color6: "#E09595"
    readonly property color color7: "#E7C2C2"
    readonly property color color8: "#A28787"
    readonly property color color9: "#910000"
    readonly property color color10: "#B80C0C"
    readonly property color color11: "#C83333"
    readonly property color color12: "#D65151"
    readonly property color color13: "#E46F6F"
    readonly property color color14: "#E09595"
    readonly property color color15: "#E7C2C2"
}
